export default {
  login: "PranavKalwad",
  id: 70849056,
  node_id: "MDQ6VXNlcjcwODQ5MDU2",
  avatar_url: "https://avatars.githubusercontent.com/u/70849056?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/PranavKalwad",
  html_url: "https://github.com/PranavKalwad",
  followers_url: "https://api.github.com/users/PranavKalwad/followers",
  following_url:
    "https://api.github.com/users/PranavKalwad/following{/other_user}",
  gists_url: "https://api.github.com/users/PranavKalwad/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/PranavKalwad/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/PranavKalwad/subscriptions",
  organizations_url: "https://api.github.com/users/PranavKalwad/orgs",
  repos_url: "https://api.github.com/users/PranavKalwad/repos",
  events_url: "https://api.github.com/users/PranavKalwad/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/PranavKalwad/received_events",
  type: "User",
  site_admin: false,
  name: "Pranav Kalwad",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Computer Science Major  at PES University",
  twitter_username: null,
  public_repos: 45,
  public_gists: 0,
  followers: 91,
  following: 159,
  created_at: "2020-09-06T13:48:57Z",
  updated_at: "2022-07-01T14:53:50Z",
}
